### PR TITLE
adding kirtiraj22

### PR DESCRIPTION
**Pull request by kirtiraj22**

### CODE REVIEW

**Comment by parasg1999** [comment]
Hi! Looks like you added 2 files. Can you please correct that?

**Comment by kirtiraj22** [comment]
@parasg1999 shall i create another pull request for that??

**Comment by parasg1999** [comment]
You can go to the main branch of your local repo, and make your changes
Then you can create another commit to your main branch. It will be updated here

**Comment by kirtiraj22** [comment]
hey @parasg1999 i have made the required changes can you check it?

**Comment by parasg1999** [comment]
LGTM! 🎉
Thank you for contributing :)

**Pull request merged**
